config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  concern :paginatable do
    get '((page/:page)(/view/:view))', action: :index, on: :collection
  end

  resources :pictures,
            concerns: %i[paginatable],
            only: %i[index new create]

  get '/about', to: 'articles#about', as: 'about'
  root to: 'articles#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
# Class for holding pictures using Paperclip gem
class Picture < ApplicationRecord
  DEFAULT_STYLES = {
    thumb: '100x100>',
    small: '200x200>',
    medium: '300x300>'
  }.freeze

  has_attached_file :image, styles: DEFAULT_STYLES
  has_attached_file :processed_image, styles: DEFAULT_STYLES

  validates :name, presence: true
  validates :description, length: { maximum: 255, allow_blank: true }

  validates_attachment :image,
                       presence: true,
                       content_type: {
                         content_type: %r{\Aimage\/.*\z}
                       }
  validates_attachment :processed_image,
                       content_type: {
                         content_type: %r{\Aimage\/.*\z}
                       },
                       allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# Controller class for "static" content
class ArticlesController < ApplicationController
  # GET /
  def welcome; end

  # GET /articles/about
  def about; end
end

app/controllers/pictures_controller.rb
# frozen_string_literal: true

# Controller class for the Picture model
class PicturesController < ApplicationController
  # GET /pictures
  def index
    @options = {
      current_page: params[:page] || 1,
      layout: params[:view] || 'grid'
    }

    @pictures = Picture.order(created_at: :desc).page(params[:page])
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # POST /pictures
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        PictureManager.send_to_processing(@picture)

        format.html do
          flash[:success] = 'Picture was successfully uploaded.'

          redirect_to action: :index
        end
      else
        format.html do
          flash[:error] = 'Picture was not uploaded.'

          render :new
        end
      end
    end
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(
      :name,
      :description,
      :image
    )
  end
end

app/helpers/application_helper.rb
# Helper methods to be used in views and controllers
module ApplicationHelper
  # override Rails defaults with Bootstrap-specific alerts
  def flash_class(level)
    alert_class_common = 'alert alert-dismissible fade in'.freeze

    case level
    when 'notice' then "#{alert_class_common} alert-info"
    when 'success' then "#{alert_class_common} alert-success"
    when 'error' then "#{alert_class_common} alert-danger"
    when 'alert' then "#{alert_class_common} alert-warning"
    else alert_class_common
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def setup_picture(picture = nil)
    return Picture.new if picture.nil?

    picture
  end
end

app/views/articles/about.html.erb
<div class="jumbotron drop-shadow">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag 'logo.png', class: 'img-responsive', alt: 'InstaVision Logo' %>
      </div>
      <div class="col-md-8">
        <h1 class="display-3">About InstaVision</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p>
          InstaVision is a simple website showcasing the power of image analysis provided by Cloud Vision from Google&reg;
        </p>
        <p>
          For further information please visit:
          <a href="https://cloud.google.com/vision/" target="_blank">Google Cloud Vision</a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/articles/welcome.html.erb
<div class="jumbotron drop-shadow">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag 'logo.png', class: 'img-responsive', alt: 'InstaVision Logo' %>
      </div>
      <div class="col-md-8">
        <h1 class="display-3">Welcome to InstaVision!</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p>Reveal the hidden secrets behind your pictures!</p>
        <p>Gathering information about your pictures has never been so easy before.</p>
        <p>Apply facial and landmark recognition powered by Google&reg;'s neural networks.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default drop-shadow">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed btn-primary" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar bar-primary"></span>
      <span class="icon-bar bar-primary"></span>
      <span class="icon-bar bar-primary"></span>
    </button>
    <%= link_to image_tag('logo.png', alt: 'InstaVision Logo'), root_path, class: 'navbar-brand' %>
  </div>
  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if current_page?(pictures_path) %>">
        <%= link_to 'Pictures', pictures_path %>
      </li>
      <li class="<%= 'active' if current_page?(about_path) %>">
        <%= link_to 'About', about_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>InstaVision</title>

    <%= favicon_link_tag %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <footer class="footer drop-shadow">
      <div class="container-fluid">
        <p class="text-muted text-center copyright-notice">&copy;&nbsp<%= Time.current.year %>&nbsp;Krzysztof Karski</p>
      </div>
    </footer>
    <%= yield :javascript %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_for setup_picture(picture), html: { role: 'form', multipart: true } do |form| %>
  <% if picture.errors.any? %>
    <div id="error-explanation">
      <h3><%= pluralize(picture.errors.count, 'error') %> prohibited this picture from being processed:</h3>
      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter name' %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', placeholder: 'Enter description' %>
  </div>
  <div class="form-group">
    <%= form.label :image %>
    <div class="input-group">
      <label class="input-group-btn">
        <span class="btn btn-primary">
          Browse
          <%= form.file_field :image, class: 'form-control hidden' %>
        </span>
      </label>
      <input type="text" id="filename-container" class="form-control" readonly="readonly">
    </div>
  </div>
  <div class="actions">
    <%= link_to pictures_path, class: 'btn btn-lg btn-default pull-left' do %>
      <span class="glyphicon glyphicon-list"></span>&nbsp;Pictures
    <% end %>
    <%= form.submit 'Submit', class: 'btn btn-lg btn-primary pull-right' %>
  </div>
<% end %>

<script>
    $(document).on('change', ':file', function () {
        const label = $(this).val().replace(/\\/g, '/').replace(/.*\//, '');

        $('#filename-container').val(label);
    });
</script>

app/views/pictures/edit.html.erb
<div class="panel panel-default drop-shadow">
    <div class="panel-heading">
        <h1 class="text-primary">Editing picture <%= @picture.name %></h1>
    </div>
    <div class="panel-body">
        <%= render 'form', picture: @picture %>
    </div>
</div>

app/views/pictures/index.html.erb
<% grid_view = @options[:layout] == 'grid' %>
<div class="jumbotron drop-shadow">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag 'logo.png', class: 'img-responsive', alt: 'InstaVision Logo' %>
      </div>
      <div class="col-md-8">
        <h1 class="display-3">Pictures</h1>
        <p>
          Here you can view the list of all uploaded pictures.
          To see the result of facial recognition simply click on a picture and click on its right side (or simply
          click the right arrow button on the keyboard).
        </p>
        <p>
          If you wish to add a new one all you have to do is
          <%= link_to new_picture_path, class: 'btn btn-lg btn-primary' do %>
            Upload
          <% end %>
        </p>
        <p>
          <%= link_to url_for(action: :index, page: @options[:current_page], view: 'grid'),
                      class: "btn btn-lg#{grid_view ? ' btn-primary' : ' btn-default'}" do %>
            <span class="glyphicon glyphicon-th"></span>
          <% end %>
          <%= link_to url_for(action: :index, page: @options[:current_page], view: 'list'),
                      class: "btn btn-lg#{grid_view ? ' btn-default' : ' btn-primary'}" do %>
            <span class="glyphicon glyphicon-th-list"></span>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <% pictures_in_group = grid_view ? 3 : 1 %>
  <% @pictures.in_groups_of(pictures_in_group, false) do |picture_group| %>
  <div class="row">
    <% picture_group.each do |picture| %>
      <div class="<%= grid_view ? 'col-md-4' : 'col-md-12' %>">
        <div class="thumbnail drop-shadow image-panel">
          <%= link_to picture.image.url,
                      data: {
                          lightbox: picture.id,
                          alt: picture.name,
                          title: picture.description
                      } do %>
            <%= image_tag picture.image.url(grid_view ? :medium : nil), class: 'panel-image' %>
            <div class="caption">
              <h3><%= picture.name %></h3>
              <p><%= picture.description %></p>
            </div>
          <% end %>
          <% if picture.processed_image.present? %>
          <%= link_to 'Processed picture', picture.processed_image.url,
                      data: {
                          lightbox: picture.id,
                          alt: "#{picture.name} (processed)",
                          title: 'Run through face recognition'
                      },
                      class: 'hidden'
          %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
  <div class="row">
    <div class="col-md-12 text-center">
      <%= paginate @pictures %>
    </div>
  </div>
</div>

<%= javascript_include_tag 'lightbox' %>

app/views/pictures/new.html.erb
<div class="jumbotron drop-shadow">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag 'logo.png', class: 'img-responsive', alt: 'InstaVision Logo' %>
      </div>
      <div class="col-md-8">
        <h1 class="display-3">Picture upload</h1>
        <p>Here you can upload your pictures.</p>
        <p>They will be sent to Google Vision for analysis.</p>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default drop-shadow">
  <div class="panel-body">
    <%= render 'form', picture: @picture %>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="text-primary">Picture details for <%= @picture.name %></h3>
  </div>
  <table class="table table-striped table-bordered table-hover">
    <tr>
      <th>Description</th>
      <td><%= @picture.description %></td>
    </tr>
    <tr>
      <th>Filename</th>
      <td><%= @picture.image_file_name %></td>
    </tr>
    <tr>
      <th>Filesize</th>
      <td><%= @picture.image_file_size %></td>
    </tr>
  </table>
  <div class="panel-footer">
    <%= link_to edit_picture_path(@picture), class: 'btn btn-lg btn-default' do %>
      <span class="glyphicon glyphicon-wrench"></span>
    <% end %>
    <%= link_to picture_path(@picture), method: :delete, class: 'btn btn-lg btn-danger pull-right' do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </div>
</div>